### ISSUE TITLE
After installing Combojack, Laptop didn't boot

### ISSUE THREAD

**Issue by Himanshuux** [uttusharma/Xiaomi-Notebook14-Hackintosh#10]
I installed Combojack after following the documentation and rebooted.

On rebooting, no bootable drive found error appeared and I had to reinstall the Bigsur

**Comment by uttufy** [comment]
> ombojack after following the documentation and rebooted.
> 
> On rebooting, no bootable drive found error appe
 ----
I stumbled upon the same thing when I was trying it on Mac Monterey beta
the issue is caused by macOS not allowing to load combojack that causes a loop where boot kept retrying loading it.

Use [ALCPlugFix ](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/main/ALCPlugFix)

**Comment by Himanshuux** [comment]
@uttusharma , did you have success installing Combojack on Bigsur?

**Comment by uttufy** [comment]
> you have success installing Combojack on Bigsur?


Yes 
I did install alcplugfix first though
