### ISSUE TITLE
No issue but question

### ISSUE THREAD

**Issue by AtharvShinde** [uttusharma/Xiaomi-Notebook14-Hackintosh#11]
Can I use your EFI for Mi Notebook 14 E-learning edition (I3 10110U) ???

**Comment by uttufy** [comment]
Yes, you can use it but some of the SSDT patches needed to be replaced to make sleep-wake work.

- [https://www.youtube.com/watch?v=2vTz9YIO8tY](https://www.youtube.com/watch?v=2vTz9YIO8tY)
- [https://www.youtube.com/watch?v=PuzbYx9ZQfc&t=1s](https://www.youtube.com/watch?v=PuzbYx9ZQfc&t=1s)
