### ISSUE TITLE
Bluetooth doesn`t working on monterey (

### ISSUE THREAD

**Issue by michitta** [uttusharma/Xiaomi-Notebook14-Hackintosh#12]
Does not work on this EFI
![image](https://user-images.githubusercontent.com/17436886/145166938-b05844c4-2cfb-4621-b158-d9f0e53aedff.png)

**Comment by aadil-sengupta** [comment]
Hey, try my EFI, here's the repo

I havent finished the repo yet but the EFI works

https://github.com/PhantomZNeuroX/Mi-Notebook-14-Horizon-Edition-Hackintosh

**Comment by uttufy** [comment]
Please update to the latest kext of [ITLWM](https://github.com/OpenIntelWireless/itlwm), [IntelBluetoothFirmware](https://github.com/OpenIntelWireless/IntelBluetoothFirmware) also add [BlueToolFixup.kext](https://github.com/acidanthera/BrcmPatchRAM)

**Comment by uttufy** [comment]
The issue has been resolved. It was caused due to ECEnabler.kext
