### ISSUE TITLE
Touchpad does not work(

### ISSUE THREAD

**Issue by michitta** [uttusharma/Xiaomi-Notebook14-Hackintosh#13]
![image](https://user-images.githubusercontent.com/17436886/146432915-53d9a070-505d-4fff-853d-50c4654d7edf.png)
It seems like in the build from November 14, everything worked on Monterey, but now my mouse 0_0 does not move

**Comment by uttufy** [comment]
Thanks for pointing out the issue. I am working to resolve this issue.

**Comment by uttufy** [comment]
I could not reproduce this issue on my machine.
