### ISSUE TITLE
Efi  i7 10gen mi notebook 14

### ISSUE THREAD

**Issue by Shubham00117** [uttusharma/Xiaomi-Notebook14-Hackintosh#2]
Please provide efi folder for i7 10gen mi notebook 14  i not able to boot I am using your efi provide you email address for help

**Comment by chipwizz** [comment]
Hi Shubham, I think Utkarsh already provided  EFI folder..
https://github.com/uttusharma/Xiaomi-Notebook14-Hackintosh/tree/master/EFI/

I am sure you already verified required bios settings. I just dropped EFI folder on to boot partition of USBpendrive and updated plist and i was able to boot. Though to make everything work properly one need to patch DSDT/SSDTs which i still was not able to manage :)

**Comment by Shubham00117** [comment]
Plese provide your telegram name i share may efi

**Comment by chipwizz** [comment]
I am very sorry Shubham but i am not on telegram. I belong to old generation :), hope you understand. if ok with you i can share my EFI folder as zip ant put it in net and share link. 

Edit: Uploaded EFI folder, 
http://s000.tinyupload.com/index.php?file_id=13478148292571731095

**Comment by chipwizz** [comment]
Hi Utkarsh, 
If possible can you please guide me to patch DSDT, especially for touchpad. I have extracted DSDT and SSDTs using cover boot. Got them decrypted using iASL with rehab's refs.txt method. Since i have already catalina running i can use MACiasl to patch. Can you please help me with - 
1. Proper sequence of patches. which patch come first and which is next. 
2. if you can mention what are the desired patched that needs to be applied for Mi NoteBook 14 Horizon.  
3. what else will be needed for ELAN touchpad to work
4. for Wifi, i am not able to connect to my hidden network (non broadcasting) however can connect to visible wifi (broadcasting) such as my cellphone hotspot. bit wierd :), Let me know if you have solution. 

so far i was referring to https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/

**Comment by uttufy** [comment]
> Hi Utkarsh,
> If possible can you please guide me to patch DSDT, especially for touchpad. I have extracted DSDT and SSDTs using cover boot. Got them decrypted using iASL with rehab's refs.txt method. Since i have already catalina running i can use MACiasl to patch. Can you please help me with -
> 
> 1. Proper sequence of patches. which patch come first and which is next.
> 2. if you can mention what are the desired patched that needs to be applied for Mi NoteBook 14 Horizon.
> 3. what else will be needed for ELAN touchpad to work
> 4. for Wifi, i am not able to connect to my hidden network (non broadcasting) however can connect to visible wifi (broadcasting) such as my cellphone hotspot. bit wierd :), Let me know if you have solution.
> 
> so far i was referring to https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/


1.  These video will help you as they helped me also
https://www.youtube.com/watch?v=3aN1yuJEhYw&t=88s
https://www.youtube.com/watch?v=hFhvLkVU_kU&t=1668s
2. Just the common patches from https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/
3.  Voodoo Kext from https://github.com/uttusharma/Xiaomi-Notebook14-Hackintosh/tree/master/BigSurOC/EFI/OC/Kexts
I recommend that you download kexts from the repo as they are correct version and well tested.
4. Refer here https://github.com/OpenIntelWireless/itlwm/issues/100

**Comment by uttufy** [comment]
Well can you mention which clover version you used to dump DSDT/SSDT because I tried with clover but my system doesn't dump with clover.

**Comment by chipwizz** [comment]
Thanks for replying. i have partitioned usbdrive with 2 bootable partitions. 1 for opencore and other for clover. here is link to my both folders. 
https://drive.google.com/drive/folders/1D80Lymji8JKhDjD2lgpZi74hv0vX1n7u?usp=sharing

**Comment by VRohit1901** [comment]
Guys, I hear some sort of buzzing sounds from my laptop(I believe from the motherboard) while booting mac os, is that anyway harmful to my laptop?

**Comment by uttufy** [comment]
> Guys, I hear some sort of buzzing sounds from my laptop(I believe from the motherboard) while booting mac os, is that anyway harmful to my laptop?

Check your ALC id in EFI config.plist also apply HeadphoneJackFix
