### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ironmanopo** [uttusharma/Xiaomi-Notebook14-Hackintosh#3]
I am a beginner and i want to buy a laptop for hackintosh under 50k can u pls give any suggestion and also help me to install hackintosh i would consider mi notebook or any other u say

**Comment by uttufy** [comment]
> I am a beginner and I want to buy a laptop for Hackintosh under 50k can u pls give any suggestion and also help me to install Hackintosh I would consider mi notebook or any other u say

I cannot recommend the best laptop for Hackintosh.But when you are purchasing one I would suggest going for intel processor-based laptops then you need to do some search regarding that Hackintosh version of that laptop check for bugs and issues. Go for that model which has the least amount of bug/issues in Hackintosh.

If you are going for notebook 14 then to need some knowledge of decompiling/ compiling /patching DSDT/SSDT.

**Comment by ironmanopo** [comment]
I want to buy a laptop with i3 10th gen in india can u pls suggest a laptop with very less bugs

**Comment by uttufy** [comment]
> I want to buy a laptop with i3 10th gen in india can u pls suggest a laptop with very less bugs

I won't be helping you with that you need to  do it by yourself:
1. make a list of laptop that you think is good
2. search for there hackintosh repo on GitHub
3. check which has very less bug

**Comment by ironmanopo** [comment]
Do u live in delhi??
