### ISSUE TITLE
My Mac OS is not showing in picker

### ISSUE THREAD

**Issue by Unforgettablepl** [uttusharma/Xiaomi-Notebook14-Hackintosh#7]
I have the horizon edition i7 model and I tried the Big Sur efi but it doesn't allow me to boot into mac os recovery. I have attached the screenshot of what is happening.
![20210508_201349](https://user-images.githubusercontent.com/50578500/117543439-82900380-b03a-11eb-8d49-06b60cc12957.jpg)
![20210508_201342](https://user-images.githubusercontent.com/50578500/117543445-87ed4e00-b03a-11eb-8fea-04009dbbf9c4.jpg)

**Comment by uttufy** [comment]
Press Spacebar to show recovery
