### ISSUE TITLE
Severe lag using macOS HiDPI

### ISSUE THREAD

**Issue by TonyPSR** [uttusharma/Xiaomi-Notebook14-Hackintosh#8]
How to replicate?
1. Play a 1080p 60fps or 4k 30fps video on Safari or Chrome. 
2. Open launchpad or switch virtual desktop.
3. Observe the stuttering.

I'm not sure if it's a limitation of Intel UHD 620 iGPU. I wanted to make sure that it's not an issue with my particular hardware. Without using the one-key-hidpi, the UI is silky smooth. But everything looks too small.

I know HiDPI consumes more resources as it essentially renders two times the resolution selected and down samples. But I'm confused how older MacBooks can do HiDPI on much high resolution monitors.

**Comment by uttufy** [comment]
> How to replicate?
> 
> 1. Play a 1080p 60fps or 4k 30fps video on Safari or Chrome.
> 2. Open launchpad or switch virtual desktop.
> 3. Observe the stuttering.
> 
> I'm not sure if it's a limitation of Intel UHD 620 iGPU. I wanted to make sure that it's not an issue with my particular hardware. Without using the one-key-hidpi, the UI is silky smooth. But everything looks too small.
> 
> I know HiDPI consumes more resources as it essentially renders two times the resolution selected and down samples. But I'm confused how older MacBooks can do HiDPI on much high resolution monitors.

Hello,
I didn't observe any shuttering It only happens after the device goes to sleep. 
In your case, the issue is may be caused by hardware acceleration failing.
[REFER HERE TO CHECK HARDWARE ACC.](https://dortania.github.io/OpenCore-Post-Install/universal/drm.html)

**Comment by TonyPSR** [comment]
Hardware acceleration working well. No issues. But there is lot of lag using HiDPI.

**Comment by uttusharma** [comment]
> Hardware acceleration working well. No issues. But there is lot of lag using HiDPI.

I am looking into this issue

**Comment by uttufy** [comment]
[REFER HERE ](https://github.com/xzhih/one-key-hidpi/issues/194)

It a known issue when using one-key-hidpi I would suggest removing One-Key-HiDPI as It is causing many issues like underscaling of screen after sleep and screen flickering.

**Comment by TonyPSR** [comment]
Thanks a lot bro.
