### ISSUE TITLE
Sleep not working?

### ISSUE THREAD

**Issue by aadil-sengupta** [uttusharma/Xiaomi-Notebook14-Hackintosh#9]
Sleep not working?

**Comment by aadil-sengupta** [comment]
After trying the opencore version 5 EFI, Sleep is working but the trackpad dosent work ;/ . evreything in the 6.7 version is working fine for me except sleep, is there a way for me to get sleep on the 6.7 version?

or for me to fix my trackapad in version 5?, I aldredy tried patching dsdt's using SSDT time but my trackpad still wasnt working

**Comment by uttufy** [comment]
You need to rebuild the kext cache after every system update. Use `Kext Utility.app` or type `sudo kextcache -i /` in `Terminal.app`. Then restart. If this still doesn't work, try to press F9.

I am working on a new efi will be releasing it this week.
It will fix 
- Sleep Problem
- Trackpad issue 
- Power management

**Comment by uttufy** [comment]
Are you using [One-key-HiDPI](https://github.com/xzhih/one-key-hidpi )?

**Comment by aadil-sengupta** [comment]
> Are you using [One-key-HiDPI](https://github.com/xzhih/one-key-hidpi )? 
> 

Nopt yet, will try tommorow

**Comment by uttufy** [comment]
> > Are you using [One-key-HiDPI](https://github.com/xzhih/one-key-hidpi)?
> 
> Nopt yet, will try tommorow

Don't use one-key-HiDPI It will surely cause sleep/wake issue.

**Comment by d-kanti** [comment]
Hey @uttusharma, can you please do something about the sleep issue. It stays in a sleep-wake cycle. We tried a lot but nothing seems to work. Though we are not so much familiar,  we need help of your expertise. Please,
1. Do you have any solution ?
2. Does sleep work for you ? if yes, what model do you own ? 
3. You said of releasing a new efi, when will you release that ? Does that fix the issue ?

**Comment by uttufy** [comment]
> Hey @uttusharma, can you please do something about the sleep issue. It stays in a sleep-wake cycle. We tried a lot but nothing seems to work. Though we are not so much familiar, we need help of your expertise. Please,
> 
> 1. Do you have any solution ?
> 2. Does sleep work for you ? if yes, what model do you own ?
> 3. You said of releasing a new efi, when will you release that ? Does that fix the issue ?

1 .  [https://github.com/uttusharma/Xiaomi-Notebook14-Hackintosh/releases/tag/v1.0.0](https://github.com/uttusharma/Xiaomi-Notebook14-Hackintosh/releases/tag/v1.0.0)
2. Yes sleep is working fine for me. My model is Notebook 14 Horizon edition (i5) 
3.  Yes the newer [EFI](https://github.com/uttusharma/Xiaomi-Notebook14-Hackintosh/releases/tag/v1.0.0) fixes these issues.
Also before trying the above efi remember to **clean NvRAM first** before booting into the os.

**Comment by d-kanti** [comment]
@uttusharma  can you guide me a little about how to clear the nvram ?  As far i remember i didn't see any option...

**Comment by d-kanti** [comment]
@uttusharma   also how did you installed the mac ?  Which process did you follow.... That might matter....

**Comment by uttufy** [comment]
> out how to clear the nvram ? As far i remember i didn't see any option...

At the time of OC boot menu (Picker) press the spacebar to reveal aux. options.

>@uttusharma also how did you installed the mac ? Which process did you follow.... That might matter....

[https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos)

**Comment by aadil-sengupta** [comment]
Hello, @uttusharma I suppose that i have found out the reason why sleep isnt working for me, The main difference between my system and a different system with sleep working is that i upgraded from Catalina to Big Sur. I heard a similar problem with  someone with a non-horizon as well.

Also i have been trying to update to MacOS Monterey but am having a issue in that, first time I ran the Monterey installer, it created another partition named "Macintosh OS" or somethin like that and i booted to it, after a few mins of code the it restarted and then I picked MacOS and it showed me the Apple logo with a "x minuites remaining" but nothing happend I just booted to big sur. Booting to the Macintosh OS partition again jus reboots. and choosing the MacOS option boots MacOS normally. Pls Help :)

**Comment by chadify** [comment]
> > Hey @uttusharma, can you please do something about the sleep issue. It stays in a sleep-wake cycle. We tried a lot but nothing seems to work. Though we are not so much familiar, we need help of your expertise. Please,
> > 
> > 1. Do you have any solution ?
> > 2. Does sleep work for you ? if yes, what model do you own ?
> > 3. You said of releasing a new efi, when will you release that ? Does that fix the issue ?
> 
> 1 . https://github.com/uttusharma/Xiaomi-Notebook14-Hackintosh/releases/tag/v1.0.0
> 2. Yes sleep is working fine for me. My model is Notebook 14 Horizon edition (i5)
> 3. Yes the newer [EFI](https://github.com/uttusharma/Xiaomi-Notebook14-Hackintosh/releases/tag/v1.0.0) fixes these issues.
> Also before trying the above efi remember to **clean NvRAM first** before booting into the os.

Can you tell me what exactly you did to fix the sleep issue? Did you patch your DSDT as well? I've i7 horizon version, sleep does not work when using your efi.

**Comment by chadify** [comment]
> Hello, @uttusharma I suppose that i have found out the reason why sleep isnt working for me, The main difference between my system and a different system with sleep working is that i upgraded from Catalina to Big Sur. I heard a similar problem with someone with a non-horizon as well.
> 
> Also i have been trying to update to MacOS Monterey but am having a issue in that, first time I ran the Monterey installer, it created another partition named "Macintosh OS" or somethin like that and i booted to it, after a few mins of code the it restarted and then I picked MacOS and it showed me the Apple logo with a "x minuites remaining" but nothing happend I just booted to big sur. Booting to the Macintosh OS partition again jus reboots. and choosing the MacOS option boots MacOS normally. Pls Help :)

Is sleep working on your Hack?

**Comment by aadil-sengupta** [comment]
> > Hello, @uttusharma I suppose that i have found out the reason why sleep isnt working for me, The main difference between my system and a different system with sleep working is that i upgraded from Catalina to Big Sur. I heard a similar problem with someone with a non-horizon as well.
> > Also i have been trying to update to MacOS Monterey but am having a issue in that, first time I ran the Monterey installer, it created another partition named "Macintosh OS" or somethin like that and i booted to it, after a few mins of code the it restarted and then I picked MacOS and it showed me the Apple logo with a "x minuites remaining" but nothing happend I just booted to big sur. Booting to the Macintosh OS partition again jus reboots. and choosing the MacOS option boots MacOS normally. Pls Help :)
> 
> Is sleep working on your Hack?

Nope ;| , Its so odd that sleep is working on a few systems but isn't on most. I still dont see any difference
